<?php

declare(strict_types=1);

namespace App\Infra\Others;

abstract class Instituition
{
    public static function get(): array
    {
        return [
            "ACADEMIA ESTADUAL DE SEGURANÇA PÚBLICA DO CEARÁ (AESP/CE)",
            "AGÊNCIA DE DEFESA AGROPECUÁRIA DO ESTADO DO CEARÁ (ADAGRI)",
            "AGÊNCIA DE DESENVOLVIMENTO DO CEARÁ S/A (ADECE)",
            "AGÊNCIA REGULADORA DE SERVIÇOS PÚBLICOS DELEGADOS DO ESTADO DO CEARÁ (ARCE)",
            "ALECE - ASSEMBLEIA LEGISLATIVA DO ESTADO DO CEARÁ",
            "ASSESSORIA ESPECIAL DA VICE-GOVERNADORIA (VICEGOV)",
            "CASA CIVIL (CC)",
            "CENTEC - INSTITUTO CENTRO DE ENSINO TECNOLÓGICO",
            "CENTRAIS DE ABASTECIMENTO DO CEARÁ S.A. (CEASA)",
            "CIDH - CENTRO INTEGRADO DE DIABETES E HIPERTENSÃO",
            "CODECE - COMPANHIA DE DESENVOLVIMENTO DO CEARÁ",
            "COHAB - COMPANHIA DE HABITAÇÃO DO ESTADO DO CEARÁ",
            "COMPANHIA ADMINISTRADORA DA ZONA DE PROCESSAMENTO DE EXPORTAÇÃO DO CEARÁ (ZPE CEARÁ)",
            "COMPANHIA CEARENSE DE TRANSPORTES METROPOLITANOS (METROFOR)",
            "COMPANHIA DA GESTÃO DOS RECURSOS HÍDRICOS DO ESTADO DO CEARÁ (COGERH)",
            "COMPANHIA DE ÁGUA E ESGOTO DO CEARÁ (CAGECE)",
            "COMPANHIA DE DESENVOLVIMENTO DO COMPLEXO INDUSTRIAL E PORTUÁRIO DO PECÉM (CIPP S/A)",
            "COMPANHIA DE GÁS DO CEARÁ (CEGÁS)",
            "COMPANHIA DE PARTICIPAÇÃO E GESTÃO DE ATIVOS DO CEARÁ (CEARAPAR)",
            "CONSELHO ESTADUAL DE EDUCAÇÃO (CEE)",
            "CONTROLADORIA E OUVIDORIA GERAL DO ESTADO (CGE)",
            "CONTROLADORIA-GERAL DE DISCIPLINA DOS ÓRGÃOS DE SEGURANÇA PÚBLICA E SISTEMA PENITENCIÁRIO DO ESTADO DO CEARÁ (CGD)",
            "CORPO DE BOMBEIROS MILITAR DO CEARÁ (CBMCE)",
            "DEFENSORIA PÚBLICA DO ESTADO DO CEARÁ",
            "DEPARTAMENTO ESTADUAL DE TRÂNSITO (DETRAN)",
            "DPGE - DEFENSORIA PÚBLICA GERAL DO ESTADO DO CEARÁ",
            "EMPRESA DE ASSISTÊNCIA TÉCNICA E EXTENSÃO RURAL DO CEARÁ (EMATERCE)",
            "EMPRESA DE TECNOLOGIA DA INFORMAÇÃO DO CEARÁ (ETICE)",
            "ESCOLA DE GESTÃO PÚBLICA DO ESTADO DO CEARÁ (EGPCE)",
            "ESCOLA DE SAÚDE PÚBLICA (ESP/CE)",
            "FUNDAÇÃO CEARENSE DE APOIO AO DESENVOLVIMENTO CIENTÍFICO E TECNOLÓGICO (FUNCAP)",
            "FUNDAÇÃO CEARENSE DE METEOROLOGIA E RECURSOS HÍDRICOS (FUNCEME)",
            "FUNDAÇÃO DE PREVIDÊNCIA SOCIAL DOS SERVIDORES DO ESTADO DO CEARÁ (CEARAPREV)",
            "FUNDAÇÃO DE TELEDUCAÇÃO DO CEARÁ (FUNTELC)",
            "FUNDAÇÃO UNIVERSIDADE ESTADUAL DO CEARÁ (FUNECE)",
            "FUNDAÇÃO UNIVERSIDADE ESTADUAL VALE DO ACARAÚ (UVA)",
            "FUNDAÇÃO UNIVERSIDADE REGIONAL DO CARIRI (URCA)",
            "HEMOCE - CENTRO DE HEMATOLOGIA E HEMOTERAPIA DO CEARÁ",
            "IDM - INSTITUTO DRAGAO DO MAR",
            "IDT - INSTITUTO DE DESENVOLVIMENTO DO TRABALHO",
            "INSTITUTO AGROPOLOS DO CEARÁ",
            "INSTITUTO DE PESQUISA E ESTRATÉGIA ECONÔMICA DO CEARÁ (IPECE)",
            "INSTITUTO DE SAÚDE DOS SERVIDORES DO ESTADO DO CEARÁ (ISSEC)",
            "INSTITUTO DO DESENVOLVIMENTO AGRÁRIO DO CEARÁ (IDACE)",
            "INSTITUTO MIRANTE DE CULTURA E ARTE",
            "IPC - INSTITUTO ESCOLA SUPERIOR DE CONTAS E GESTÃO PÚBLICA MINISTRO PLÁCIDO CASTELO",
            "IPCC - INSTITUTO DE PREVENÇÃO DO CÂNCER DO ESTADO DO CEARÁ",
            "ISGH - INSTITUTO DE SAÚDE E GESTÃO HOSPITALAR",
            "JUNTA COMERCIAL DO ESTADO DO CEARÁ (JUCEC)",
            "MPCE - MINISTÉRIO PÚBLICO DO ESTADO DO CEARÁ",
            "NÚCLEO DE TECNOLOGIA E QUALIDADE INDUSTRIAL DO CEARÁ (NUTEC)",
            "PERÍCIA FORENSE DO ESTADO DO CEARÁ (PEFOCE)",
            "POLÍCIA MILITAR DO CEARÁ (PMCE)",
            "PROCURADORIA-GERAL DO ESTADO (PGE)",
            "SECRETARIA DA ARTICULAÇÃO POLÍTICA (SEAPO)",
            "SECRETARIA DA CIÊNCIA, TECNOLOGIA E EDUCAÇÃO SUPERIOR (SECITECE)",
            "SECRETARIA DA CULTURA (SECULT)",
            "SECRETARIA DA DIVERSIDADE (SEDIV)",
            "SECRETARIA DA EDUCAÇÃO (SEDUC)",
            "SECRETARIA DA FAZENDA (SEFAZ)",
            "SECRETARIA DA IGUALDADE RACIAL (SEIR)",
            "SECRETARIA DA INFRAESTRUTURA (SEINFRA)",
            "SECRETARIA DA JUVENTUDE (SEJUV)",
            "SECRETARIA DA PESCA E AQUICULTURA (SPA)",
            "SECRETARIA DA PROTEÇÃO ANIMAL (SEPA)",
            "SECRETARIA DA PROTEÇÃO SOCIAL (SPS)",
            "SECRETARIA DA SAÚDE (SESA)",
            "SECRETARIA DA SEGURANÇA PÚBLICA E DEFESA SOCIAL (SSPDS)",
            "SECRETARIA DAS CIDADES (SCIDADES)",
            "SECRETARIA DAS MULHERES (SEM)",
            "SECRETARIA DAS RELAÇÕES INTERNACIONAIS (SRI)",
            "SECRETARIA DE ADMINISTRAÇÃO PENITENCIÁRIA E RESSOCIALIZAÇÃO (SAP)",
            "SECRETARIA DO DESENVOLVIMENTO AGRÁRIO (SDA)",
            "SECRETARIA DO DESENVOLVIMENTO ECONÔMICO (SDE)",
            "SECRETARIA DO ESPORTE (SESPORTE)",
            "SECRETARIA DO MEIO AMBIENTE E MUDANÇA DO CLIMA (SEMA)",
            "SECRETARIA DO PLANEJAMENTO E GESTÃO (SEPLAG)",
            "SECRETARIA DO TRABALHO (SET)",
            "SECRETARIA DO TURISMO (SETUR)",
            "SECRETARIA DOS DIREITOS HUMANOS (SEDIH)",
            "SECRETARIA DOS POVOS INDÍGENAS (SEPINCE)",
            "SECRETARIA DOS RECURSOS HÍDRICOS (SRH)",
            "SUPERINTENDÊNCIA DA POLÍCIA CIVIL (PCCE)",
            "SUPERINTENDÊNCIA DE OBRAS HIDRÁULICAS (SOHIDRA)",
            "SUPERINTENDÊNCIA DE OBRAS PÚBLICAS (SOP)",
            "SUPERINTENDÊNCIA DE PESQUISA E ESTRATÉGIA DE SEGURANÇA PÚBLICA (SUPESP)",
            "SUPERINTENDÊNCIA DO SISTEMA ESTADUAL DE ATENDIMENTO SOCIOEDUCATIVO (SEAS)",
            "SUPERINTENDÊNCIA ESTADUAL DE DEFESA DO CONSUMIDOR (PROCON-CEARÁ)",
            "SUPERINTENDÊNCIA ESTADUAL DO MEIO AMBIENTE (SEMACE)",
            "TCE - TRIBUNAL DE CONTAS DO ESTADO DO CEARÁ",
            "TJCE - TRIBUNAL DE JUSTIÇA DO ESTADO DO CEARÁ",
            "TRE - TRIBUNAL REGIONAL ELEITORAL DO CEARÁ",
        ];
    }

    public static function options(): array
    {
        // retorna ["texto" => "texto"] pra usar direto no <select>
        return collect(self::get())
            ->mapWithKeys(fn ($item) => [$item => $item])
            ->toArray();
    }
}
